spring:
  application:
    name: monitoring
  lifecycle:
    timeout-per-shutdown-phase: 20s
  messages:
    basename: i18n/message
    encoding: UTF-8
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:password}
    driver-class-name: ${DATASOURCE_CLASS_NAME:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: ${JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
otel:
  traces:
    exporter: jaeger
  exporter:
    jaeger:
      endpoint: http://${JAEGER_HOST:0.0.0.0}:${JAEGER_PORT:14250}
  metrics:
    exporter: none
  logs:
    exporter: none
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    groups-order: ASC
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true

server:
  port: 8080
  shutdown: "graceful"
  tomcat:
    connection-timeout: -1