spring:
  application:
    name: monitoring
  lifecycle:
    timeout-per-shutdown-phase: 20s
  messages:
    basename: i18n/message
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://192.168.106.104:35432/openmetadata_history
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    groups-order: ASC
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true

logging:
  level:
    root: info

server:
  port: 8080
  shutdown: "graceful"
  tomcat:
    connection-timeout: -1

scheduler:
  collect_expression: "0 0/5 * * * *"
  save_expression: "0 0/30 * * * *"
  connection_timeout: 30

open-metadata:
  path:
    database_service: "/api/v1/services/databaseServices?limit=1000000"
    storage_service: "/api/v1/services/storageServices?limit=1000000"
    query: "/api/v1/search/query"
    login: "/api/v1/users/login"
    bot: "/api/v1/bots/name/ingestion-bot"
    auth_mechanism: "/api/v1/users/auth-mechanism"
  origin: "http://192.168.106.104:8585"
  auth:
    id: "admin"
    passwd: "admin"
  pageable_config:
    history:
      page: 0
      size: 5
    connect:
      page: 0
      size: 5
    event:
      page: 0
      size: 5
    registration:
      page: 0
      size: 5
