spring:
  application:
    name: monitoring
  lifecycle:
    timeout-per-shutdown-phase: 20s
  messages:
    basename: i18n/message
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://192.168.106.104:35432/openmetadata_history
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info

server:
  port: 8080
  shutdown: "graceful"
  tomcat:
    connection-timeout: -1

entity:
  origin: "http://192.168.106.104:8585"
  save_entity_type:
    history:
      - "databaseService"
      - "databaseSchema"
      - "database"
      - "table"
      - "storageService"
      - "container"
      - "workflow"
    services:
      - "databaseService"
      - "storageService"
    services_child:
      - "databaseSchema"
      - "database"
      - "table"
      - "container"
    connect:
      - "workflow"
  auth:
    id: "admin"
    passwd: "admin"
  table:
    get: "get_URL"
    list: "list_URL"
    url: "test"
  databases_service:
    get: "asdf"
  storage_service:
    get: "get_Urlssss"
    list: "list_URl"
    unique_storage: "unique"
    name: "name"
  containers:
    get: "zaq"
  databases:
    get: "xsw"
  test_connection_definitions:
    get: "cde"
  pageable_config:
    history:
      page: 1
      size: 5
    connect:
      page: 1
      size: 5
    event:
      page: 1
      size: 5
